### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [cduerkes/firehose-2-2#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by cduerkes** [comment]
Thanks. I put the viewport meta tag in the header, but don't really see a difference. What is it about the mobile view that you think could use improving?

**Comment by Mikeysax** [comment]
https://v4-alpha.getbootstrap.com/getting-started/introduction/#responsive-meta-tag

It depends on where you look at the website, but generally for the styles to appear properly on mobile, you will need to use this tag.

Good job adding it 👍
